#!/bin/bash
set -e
# check HTML, JS, CSS
make html

# check for broken link
python -m http.server 8001 --directory output &> /dev/null & pid=$!
sleep 1
pylinkvalidate.py http://localhost:8001/
kill "${pid}"

# openwisp-utils checks
openwisp-qa-check \
    --skip-checkmigrations \
    --skip-checkmakemigrations \
    --skip-checkendline \
